name: Test matrix

on:
  workflow_dispatch:
    inputs:
      one:
        type: boolean
        default: true
      two:
        type: boolean
        default: true

jobs:
  prepare-job:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "matrix=$(echo '${{ toJSON(inputs) }}' | jq -c '[to_entries[] | select(.value).key]')" >> $GITHUB_OUTPUT
  matrix-job:
    needs: prepare-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{ fromJSON(needs.prepare-job.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.label }}
