name: Test matrix

on:
  workflow_dispatch:
    inputs:
      one:
        type: boolean
        default: true
      two:
        type: boolean
        default: true

jobs:
  prepare-job:
    runs-on: ubuntu-latest
    steps: 
      - run: echo '${{ toJSON(inputs) }}'
  matrix-job:
    needs: prepare-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{ inputs.* }}
    steps:
      - run: echo ${{ matrix.label }}
