# This is a basic workflow to help you get started with Actions

name: Trigger Update

on:
  # usually, this would be the commented part - however, for testing we need the other one.
  workflow_dispatch:
  # push:
    # branches: [ main ]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: List Files
        run: ls
      - name: Zip
        run: zip test.zip *
      - name: Upload Zip File
        run: curl -X POST -F 'zip=@test.zip' https://crazypokemondev.de:5000/api/self/update
